### ISSUE TITLE
Did the server just crash? All me and my friends snap cameras are not working not even the cached versions seem to work

### ISSUE THREAD

**Issue by EolnMsuk** [jaku/SnapCameraPreservation#111]
Please fix server issue it no work no more

**Comment by nvaclark** [comment]
Same here

**Comment by russell-gh** [comment]
Yes, I have the same issue!

**Comment by jaku** [comment]
There was a DDOS against the server today, and with 2 million active users and the DDOS traffic it was difficult to pick out who was attacking and who was trying to use it.

In any case it should be resolved now, reboot your computer or completely kill the process from task manager and reopen it and it should be working again.

**Comment by allandriah** [comment]
Still isnt working for me. the filters just disappear when i click them

**Comment by jaku** [comment]
> Still isnt working for me. the filters just disappear when i click them

Cannot replicate that, did you close the process or reboot? Try rebooting.

**Comment by russell-gh** [comment]
IT WORKS!

**Comment by lackadysium** [comment]
> > Still isnt working for me. the filters just disappear when i click them
> 
> Cannot replicate that, did you close the process or reboot? Try rebooting.

I'm having the same issue, I closed the process and rebooted my PC. Still the same

**Comment by russell-gh** [comment]
Also try clearing the DNS cache.

**Comment by lackadysium** [comment]
I'm not well versed in this stuff, how does one clear DNS cache?

**Comment by russell-gh** [comment]
To flush the DNS on Windows, open Command Prompt as an administrator and type the command ipconfig /flushdns, then press Enter. This will clear the DNS cache and help resolve any connectivity issues.

Then reboot and you can also try reinstalling.

**Comment by lackadysium** [comment]
I did all of that, I even uninstalled and reinstalled and it's still not working :(

**Comment by ava-gunn** [comment]
In MacOS 15.4.1, cleared DNS cache and rebooted and still not working. Filter images in starred filters popout don't load, and clicking on them doesn't apply them.

**Comment by Loomis360** [comment]
I tried to use it last night and it's like the entire program factory reset. No filters, so starred filters, no hotkeys. I have filters cached on another drive that I tried copying over to the appropriate appdata folder, but that didn't change anything. Is it just down?

**Comment by prynetopg777** [comment]
same too
